### PR TITLE
Make the component SSRable

### PR DESCRIPTION
**Pull request by kaisermann**
I'm starting to play around with canvas and found `svelte-canvas`, so thanks for it 😁 . 

However, after trying to add it to my sapper playground I saw that it wasn't considering a server-side environment. This PR is kind of simplistic but makes it work!

~(Also not perfect, there's a loose `NaN` in the `width` and `height` props. Will fix that tomorrow from here.)~

**Screenshots:**

**Page's source code**
image

Used the example provided in the readme

### CODE REVIEW

**Comment by dnass** [comment]
Hey, thanks for this! The `t` fix looks good. In `Canvas`, I don't think that the safeguards inside `onMount` and `draw` are needed — onMount [doesn't run](https://svelte.dev/docs#onMount) on the server side, so draw won't get called either.

Good catch about `NaN` in the width and height. Moving the window check outside `onMount` should solve that:
```
if (pixelRatio === undefined) {
  if (typeof window === "undefined") pixelRatio = 2;
  else pixelRatio = window.devicePixelRatio;
}
```

If you make those tweaks, I'd be happy to merge this!

**Comment by kaisermann** [comment]
Oops! You're right. Even fewer changes now 🙌 . Done!

**Comment by dnass** [comment]
Looks good, merging!

Thanks for catching the inconsistent quotes 😅 if you want to create prettierrc that'd be great. My preference is `"singleQuote": true`

**Comment by dnass** [comment]
I just published a new version to NPM that includes your SSR fixes (I went ahead and added a prettier config too). Thanks again — you're welcome to contribute more if you have other ideas for the project.

**Pull request merged**
