### PR TITLE
Version 1.0

### PR DESCRIPTION
**Pull request by dnass**

### CODE REVIEW

**Review by LeoDog896 — COMMENTED** [review]
The demo looks incredible! Everything seems a lot more clean, too. My only nitpick is that my laptop screen is 1366x768, and I noticed that there's some margin issues at that size.

image

**Comment by dnass** [comment]
@LeoDog896 Thanks for taking a look! What browser are you using? I'm seeing a couple issues in the screenshot — the Google fonts don't seem to be loading, which is causing the version number to wrap in the sidebar, and the main content is wider than it should be.

**Comment by LeoDog896** [comment]
Firefox

**Comment by LeoDog896** [comment]
Oh, by the way, for places where Google fonts is banned, Fontsource is a great alternative.

**Comment by dnass** [comment]
Ah, the font is Source Sans 3 but I had put `font-face: "Source Sans Pro"` so really the question is, why WAS it working in Chrome? Anyway, should be fixed now.

**Pull request merged**
